parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: 'wn_pro_mysql'
    database_user: root
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5d85fc6e99f3b6d9a5985426054ca36a89eb5936
    database_path: null
