parameters:
#    acme_hangman_support.example.class: Acme\HangmanSupportBundle\Example

services:
#    acme_hangman_support.example:
#        class: %acme_hangman_support.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
