<?php

namespace Acme\HangmanSupportBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * SynetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynetRepository extends EntityRepository
{
    public static function getInstance(EntityManager $em) {
        return $em->getRepository('AcmeHangmanSupportBundle:Synet');
    }
    
    public function likeSearch($string) {
        return $this->getEntityManager()->createQuery("SELECT w FROM AcmeHangmanSupportBundle:Synet w WHERE w.word LIKE '$string'")->getResult();
    }
}
